services:
  navidrofm:
    # image: ghcr.io/4rft5/navidrofm:latest
    image: aaronp18/navidrofm
    container_name: navidrofm
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/London
      LASTFM_USERNAME: NAME
      LZ_USERNAME: NAME
      NAVIDROME_URL: http://NAVIDROME_IP:4533
      NAVIDROME_USERNAME: USERNAME
      NAVIDROME_PASSWORD: PASSWORD
      CSV_ENABLED: "true"
      SYNC_SCHEDULE: "00 4 * * 1"
      RECOMMENDED: "true"
      RECOMMENDED_TRACKS: "10"
      MIX: "true"
      MIX_TRACKS: "10"
      LIBRARY: "true"
      LIBRARY_TRACKS: "50"
      EXPLORATION: "true"
      EXPLORATION_TRACKS: "25"
      JAMS: "true"
      JAMS_TRACKS: "25"
      RUN_ON_STARTUP: "false"
      PUID: 1000
      PGID: 1000
    volumes:
      - /path/to/music:/music
      - ./cookies.txt:/app/cookies/cookies.txt
      - ./blocklist.json:/app/blocklist.json:ro #Optional
      - ./csv_playlists/:/app/csv_playlists #Optional
